create table tb_automovel (id int8 generated by default as identity, ano timestamp, cor varchar(255), modelo varchar(255), placa varchar(255), primary key (id));
create table tb_usuario (id int8 generated by default as identity, data_de_nascimento timestamp, login varchar(255), nome varchar(255), senha varchar(255), sobrenome varchar(255), primary key (id));
create table tb_usuario_automovel (automovel_id int8 not null, usuario_id int8 not null);
alter table if exists tb_usuario_automovel add constraint FKhad5g4ymveket1qaluk9k885e foreign key (usuario_id) references tb_automovel;
alter table if exists tb_usuario_automovel add constraint FK380iyln4ckeh08qw48cyfi2da foreign key (automovel_id) references tb_usuario;
